### ISSUE TITLE
No preview or page render until category selected - bug

### ISSUE THREAD

**Issue by neotrope** [mtekk/Order-Bender#11] opened 2016-07-25 23:34 UTC
If category chosen in Order Bender, renamed, existing post may not render on site, as with same behavior of preview not working until a default selected.

Possible fix would be to fall back to a master default category if none selected in O-B widget.

(e.g., default fallback to "category 1" if none other selected, or allow hard code preset to something like, oh, say ID=17, which might be "business" on a news portal)

**Comment by neotrope** [comment] 2016-07-27 14:54
ISSUE/BUG:
when no category selected, page will not render on site. Causes issue with existing or imported legacy content into new site or merging two sites.

My thinking: SOLUTION NEEDED:
add a default selector in Order Bender: "None" -- which would then cause NavXT to default to normal behavior like your Trixx plugin, so that then the normal "lowest cat with sub cat" behavior would continue.

John/sent don-a-tion to help with response :-)

Need solution ASAP for anybody able to help, if John out of pocket.

**Comment by mtekk** [comment] 2016-07-30 16:13
I'm trying to reproduce this on my testbed, but I'm having issues doing so. For the record, I am using the latest master branch of Order Bender and Breadcrumb NavXT to test this. If there isn't a preferred category set, Order Bender should do nothing for the breadcrumb trail. Seeing as you're having issues rendering pages (sounds like "white screen of death"), it sounds like a PHP error is occurring. Can you enable `WP_DEBUG`, and see what PHP errors/warnings show up?

**Comment by neotrope** [comment] 2016-07-30 16:18
Hi, John, I don't actually get a blank page; it just stops rendering the page at the breadcrumb insertion point. I'll switch on debug and see if I can create a private page to test.

**Comment by neotrope** [comment] 2016-07-30 16:24
Notice: Undefined property: WP_Error::$term_id in /var/www/vhosts/MYSITE.ooo/httpdocs/wire/assets/plugins/breadcrumb-navxt/class.bcn_breadcrumb_trail.php

**Comment by mtekk** [comment] 2016-07-30 16:26
Is there a line number associated with that PHP Notice?

**Comment by neotrope** [comment] 2016-07-30 16:31
(updated prior post)

**Comment by mtekk** [comment] 2016-07-30 16:34
Try changing line 261 in class.bcn_breadcrumb_trail.php from: `if($term !== false)` to: `if($term instanceof WP_Term)`

**Comment by neotrope** [comment] 2016-07-30 16:44
Interesting - okay, the page now renders past the breadcrumb (yay), but the breadcrumb itself doesn't pick up any of the 'normal' (not OrderBender) selected categories:

Send2Press » Wire » New Business and Marketing Podcast Creating a Digital Endurance Online

where the lowest ID and alpha selected for the story is 'Advertising' ...

which is properly picked up by everything else, like Yoast or a query I have at bottom of page to do a button link "read more advertising news" based on the first category 

and Yoast gets
`<meta property="article:section" content="Advertising" />`

so, at least the rendering issue passed ...

**Comment by mtekk** [comment] 2016-07-30 16:52
The first issue was a bug in Breadcrumb NavXT, I'm reopening the 5.5.0 milestone and delaying its release until https://github.com/mtekk/Breadcrumb-NavXT/issues/150 is closed. The deeper issue is that `get_the_terms` isn't exactly returning what we're expecting. Can you try adding the following  to class.bcn_breadcrumb_trail.php on your testbed: `var_dump($bcn_object);` after line 217 and seeing what the output is on a page that previously had the PHP messages?

**Comment by neotrope** [comment] 2016-07-30 16:56
Only way to bring back the php messages would be to undo the mod in class.bcn_breadcrumb_trail.php

**Comment by mtekk** [comment] 2016-07-30 16:58
No need to undo the previous modification. Just visit a page that used to have the error messages, the `var_dump` should provide more output around the breadcrumb trail.

**Comment by neotrope** [comment] 2016-07-30 17:01
Will do. Live site so just messing with the oldest story from the May 15 setup. One moment. .....

-------


<div class="breadcrumbs s2p-breadcrumbs" typeof="BreadcrumbList" vocab="http://schema.org/">
array(4) {
  [0]=>
  object(WP_Term)#50 (17) {
    ["term_id"]=>
    int(11)
    ["name"]=>
    string(11) "Advertising"
    ["slug"]=>
    string(26) "advertising-marketing-news"
    ["term_group"]=>
    int(0)
    ["term_taxonomy_id"]=>
    int(11)
    ["taxonomy"]=>
    string(8) "category"
    ["description"]=>
    string(201) "Advertising and Marketing News - Including news related to advertising, branding, marketing, public relations, PR, SEO, search engine marketing, and related topics from the Send2Press Newswire service."
    ["parent"]=>
    int(0)
    ["count"]=>
    int(5)
    ["filter"]=>
    string(3) "raw"
    ["object_id"]=>
    int(126)
    ["cat_ID"]=>
    int(11)
    ["category_count"]=>
    int(5)
    ["category_description"]=>
    string(201) "Advertising and Marketing News - Including news related to advertising, branding, marketing, public relations, PR, SEO, search engine marketing, and related topics from the Send2Press Newswire service."
    ["cat_name"]=>
    string(11) "Advertising"
    ["category_nicename"]=>
    string(26) "advertising-marketing-news"
    ["category_parent"]=>
    int(0)
  }
  [1]=>
  object(WP_Term)#49 (17) {
    ["term_id"]=>
    int(15)
    ["name"]=>
    string(12) "Broadcasting"
    ["slug"]=>
    string(17) "broadcasting-news"
    ["term_group"]=>
    int(0)
    ["term_taxonomy_id"]=>
    int(15)
    ["taxonomy"]=>
    string(8) "category"
    ["description"]=>
    string(144) "Broadcasting News - including radio, television, cable, internet radio, podcasts, and streaming media news from the Send2Press Newswire service."
    ["parent"]=>
    int(37)
    ["count"]=>
    int(3)
    ["filter"]=>
    string(3) "raw"
    ["object_id"]=>
    int(126)
    ["cat_ID"]=>
    int(15)
    ["category_count"]=>
    int(3)
    ["category_description"]=>
    string(144) "Broadcasting News - including radio, television, cable, internet radio, podcasts, and streaming media news from the Send2Press Newswire service."
    ["cat_name"]=>
    string(12) "Broadcasting"
    ["category_nicename"]=>
    string(17) "broadcasting-news"
    ["category_parent"]=>
    int(37)
  }
  [2]=>
  object(WP_Term)#48 (17) {
    ["term_id"]=>
    int(14)
    ["name"]=>
    string(16) "Florida Business"
    ["slug"]=>
    string(12) "florida-news"
    ["term_group"]=>
    int(0)
    ["term_taxonomy_id"]=>
    int(14)
    ["taxonomy"]=>
    string(8) "category"
    ["description"]=>
    string(204) "Florida Business News – including entertainment, finance, health and medical, non-profit, public policy and technology news from Florida, U.S.A. (Fla., FL), as issued by the Send2Press Newswire service."
    ["parent"]=>
    int(19)
    ["count"]=>
    int(16)
    ["filter"]=>
    string(3) "raw"
    ["object_id"]=>
    int(126)
    ["cat_ID"]=>
    int(14)
    ["category_count"]=>
    int(16)
    ["category_description"]=>
    string(204) "Florida Business News – including entertainment, finance, health and medical, non-profit, public policy and technology news from Florida, U.S.A. (Fla., FL), as issued by the Send2Press Newswire service."
    ["cat_name"]=>
    string(16) "Florida Business"
    ["category_nicename"]=>
    string(12) "florida-news"
    ["category_parent"]=>
    int(19)
  }
  [3]=>
  object(WP_Term)#46 (17) {
    ["term_id"]=>
    int(18)
    ["name"]=>
    string(19) "Vero Beach Business"
    ["slug"]=>
    string(15) "vero-beach-news"
    ["term_group"]=>
    int(0)
    ["term_taxonomy_id"]=>
    int(18)
    ["taxonomy"]=>
    string(8) "category"
    ["description"]=>
    string(112) "News from Vero Beach, Florida (FL) USA - Vero Beach business news, as issued by the Send2Press Newswire service."
    ["parent"]=>
    int(14)
    ["count"]=>
    int(1)
    ["filter"]=>
    string(3) "raw"
    ["object_id"]=>
    int(126)
    ["cat_ID"]=>
    int(18)
    ["category_count"]=>
    int(1)
    ["category_description"]=>
    string(112) "News from Vero Beach, Florida (FL) USA - Vero Beach business news, as issued by the Send2Press Newswire service."
    ["cat_name"]=>
    string(19) "Vero Beach Business"
    ["category_nicename"]=>
    string(15) "vero-beach-news"
    ["category_parent"]=>
    int(14)
  }
}

**Comment by mtekk** [comment] 2016-07-30 17:06
That's interesting, so this was a page that had the PHP Errors before making the `instanceof` change?

**Comment by neotrope** [comment] 2016-07-30 17:12
This is the same page I have been testing with on live site.

Initially with no OrderBender element selected, page would die at the breadcrumbs div.

With your mod to the file today, page would render past breadcrumb, but missing the main category after wire.

Also note I am using the filter trick you provided to render the site name ahead of the directory since main site is Send2Press, and the new news location is in wire, so 'wire' is the 'home' of the news directory, while Send2Press is the actual home page. 

```
add_action('bcn_after_fill', 'my_static_breadcrumb_adder');
function my_static_breadcrumb_adder($breadcrumb_trail)
{
    $breadcrumb_trail->add(new bcn_breadcrumb('Send2Press', NULL, array('home'), 'https://www.send2press.com/'));
}
```

worth noting I have no console errors in Chrome.

**Comment by neotrope** [comment] 2016-07-30 17:15
Also using Yoast filter to disable their "choose primary" as didn't work right anyway:
`add_filter( 'wpseo_primary_term_taxonomies', '__return_empty_array' );`

**Comment by mtekk** [comment] 2016-07-30 17:17
At this point, I think the following will help debuging this: try adding `var_dump($term)` before the if($term instanceof WP_Term) and posting the output (preferably for the same page as the posted output above).

**Comment by neotrope** [comment] 2016-07-30 17:21
Where is that ? Sorry.

**Comment by mtekk** [comment] 2016-07-30 17:22
Should be around line 261 in class.bcn_breadcrumb_trail.php.

**Comment by neotrope** [comment] 2016-07-30 17:28
That crashed the site. Let me know what line number to insert that. I need to run to my Jenny Craig diet program appt at 10:40, couple miles away, but will be back in 45 min. Thanks for working on this !  :-)

**Comment by mtekk** [comment] 2016-07-30 17:31
Sorry, forgot the semicolon. If you remove the `var_dump($bcn_object);` at line 217, place `var_dump($term);` after line 260, before `if($term instanceof WP_Term)`.

**Comment by neotrope** [comment] 2016-07-30 18:29
I'm back; will test in just a few minutes :-)   (( need coffee ))

**Comment by neotrope** [comment] 2016-07-30 18:39
okay
```
object(WP_Error)#524 (2) {
  ["errors"]=>
  array(1) {
    ["invalid_term"]=>
    array(1) {
      [0]=>
      string(10) "Empty Term"
    }
  }
  ["error_data"]=>
  array(0) {
  }
}
```

**Comment by mtekk** [comment] 2016-07-30 18:46
Ok, in order-bender.php, can you add `var_dump($perf_id);` after line 199 and post the output?

**Comment by mtekk** [comment] 2016-07-30 18:50
Note that I updated my above comment, had a typo in the var_dump code.

**Comment by neotrope** [comment] 2016-07-30 18:55
ok... editing Version: 0.7.0 / added to line 200
---------
```
Notice: Undefined variable: perf_id in /var/www/vhosts/send2press.com/httpdocs/wire/assets/plugins/Order-Bender-master/order-bender.php on line 200
NULL
```

**Comment by neotrope** [comment] 2016-07-30 19:00
updated to 0.7.1 - while I had it open ...

**Comment by neotrope** [comment] 2016-07-30 19:01
Hm. Actually that might have fixed something (!).

**Comment by mtekk** [comment] 2016-07-30 19:05
Looks like you may have been affected by a bug in 0.7.0 that was fixed in 0.7.1. Regardless, I also pushed an updated 0.7.2 that will ensure it does not return a non-WP_Term instance.

**Comment by neotrope** [comment] 2016-07-30 19:07
Okay.
Well, not sure why I didn't have 0.7.1 installed. Could have sworn I checked that on Thursday and made a mistake in the folder I used to upload from ... so, between 0.71 and the line 261 in the class.bcn_breadcrumb_trail.php -- it *does* appear to be working correctly.

So, this page, which right now has "no" OrderBender item selected, has the breadcrumbs fall back properly to lowest ID of category, which was expected:

`https://www.send2press.com/wire/new-business-and-marketing-podcast-creating-a-digital-endurance-online/`

I think you've (we've) done it!  :-)

**Comment by neotrope** [comment] 2016-07-30 19:09
Thank you :-)

**Comment by mtekk** [comment] 2016-07-30 19:10
Good to hear!

**Comment by neotrope** [comment] 2016-07-31 17:00
Okay ... minor wrinkle; might be fixed with new version of NavXT once live.

I noticed this morning, that one of the posts previously selected with OrderBender as primary category being "sports" is actually printing on page as if not selected; and I just tried resaving with no selection, then resaving with selected "sports and activities" again, but on page it falls back to the lowest ID as if nothing is selected:

`https://www.send2press.com/wire/teamsnap-announces-1-million-teams-now-use-its-sports-team-management-platform/`

so, on page where this WAS working properly, post fix it is not

previously 

`Send2Press » Wire » Sports and Activities » TeamSnap Announces 1 Million Teams Now Use Its Sports Team Management Platform`

after our shenanigans yesterday

`Send2Press » Wire » U.S. Business » Colorado Business » Boulder Business » TeamSnap Announces 1 Million Teams Now Use Its Sports Team Management Platform`

on the post, the item 'sports' clearly selected in the post.

Might be do to the line I changed in NavXT.

I also found this issue with another post behaving differently today.

Unique about each post category selection

1) with the sports category; sports is a parent, with child categories; parent is selected
2) with the other post, education is selected ,and is parent category with no children

So, it looks like "now" with updated version of the Order Bender, it no longer works with parent categories, ONLY with children; so even when a parent is selected, this is treated as "no selection" and falls back to lowest ID/alpha.

So in the case of the 'education' item, with 'education' selected in order bender, this one falls back to the state/city category, which is what we were trying to solve in using Order Bender.

`https://www.send2press.com/wire/rsu-74-becomes-first-maine-district-to-select-synergy/`

doh.

I will see if I can reinstall NavXT to put it back to prior behavior.

**Comment by neotrope** [comment] 2016-07-31 17:58
Note correct selected category ID is written to mob_category_prefered - in the case of the first example story, "sports..." is cat ID = 30. However the breadcrumb doesn't render that ID and falls back to "none" or default.

**Comment by mtekk** [comment] 2016-08-02 01:01
Just a heads up, it appears my intermittent Internet on Saturday caused a push to not complete. There was an issue with what was internally versioned 0.7.2, that has been resolved. Please try the latest on the master branch and see if the issue persists.

**Comment by neotrope** [comment] 2016-08-02 01:14
Oooh la la! Now that's what I'm talking about !  :-)  That fixed it.

Tested
a) select sports as primary in OB, renders breadcrumb correctly
b) same post, switch to -select- then preview, falls back to lowest ID/alpha (and renders!).

Whew :-)
Thanks for staying on top of that. 

Your combo of tools really helps with our migration from in house CMS to WP. Our old custom system was a bit more straightforward with categories selection in that we had five drop down selectors and could choose anything, and the "first" one was primary always. Simple. So, with the serialized data here, the whole 'primary' category thing has been a bit of a trick since we do need to choose multiple industries, and then a locale. 

Again, thank you !

**Closed** 2016-08-03 02:56 UTC
